//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotGDX.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotGDX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About you.
        /// </summary>
        public static string AboutYou {
            get {
                return ResourceManager.GetString("AboutYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на of players have unlocked this achievement..
        /// </summary>
        public static string AchievementPlayerUnlocked {
            get {
                return ResourceManager.GetString("AchievementPlayerUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Achievements.
        /// </summary>
        public static string Achievements {
            get {
                return ResourceManager.GetString("Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add/Edit profile.
        /// </summary>
        public static string AddEditProfile {
            get {
                return ResourceManager.GetString("AddEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a favorite game.
        /// </summary>
        public static string AddFavGame {
            get {
                return ResourceManager.GetString("AddFavGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a favorite game by clicking on the &quot;Star&quot; button on a game&apos;s card..
        /// </summary>
        public static string AddFavGameWelcome {
            get {
                return ResourceManager.GetString("AddFavGameWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a game.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a game by clicking on the &quot;Add&quot; button..
        /// </summary>
        public static string AddGameWelcome {
            get {
                return ResourceManager.GetString("AddGameWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a new profile.
        /// </summary>
        public static string AddProfile {
            get {
                return ResourceManager.GetString("AddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Steam game.
        /// </summary>
        public static string AddSteamGame {
            get {
                return ResourceManager.GetString("AddSteamGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a tag.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Microsoft Store game.
        /// </summary>
        public static string AddUWPGame {
            get {
                return ResourceManager.GetString("AddUWPGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin mode.
        /// </summary>
        public static string AdminMode {
            get {
                return ResourceManager.GetString("AdminMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advanced Gamer.
        /// </summary>
        public static string AdvancedGamer {
            get {
                return ResourceManager.GetString("AdvancedGamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play at least 100 hours, no matter which game..
        /// </summary>
        public static string AdvancedGamerDesc {
            get {
                return ResourceManager.GetString("AdvancedGamerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Badges.
        /// </summary>
        public static string AllBadges {
            get {
                return ResourceManager.GetString("AllBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string AllFilters {
            get {
                return ResourceManager.GetString("AllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always check if the game is currently running.
        /// </summary>
        public static string AlwaysCheckIfGameRunning {
            get {
                return ResourceManager.GetString("AlwaysCheckIfGameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Application Id&quot; property.
        /// </summary>
        public static string ApplicationId {
            get {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BotGDX.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Associated.
        /// </summary>
        public static string Associated {
            get {
                return ResourceManager.GetString("Associated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Associate a game.
        /// </summary>
        public static string AssociateGame {
            get {
                return ResourceManager.GetString("AssociateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Associate tags.
        /// </summary>
        public static string AssociateTags {
            get {
                return ResourceManager.GetString("AssociateTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic backup.
        /// </summary>
        public static string AutoSave {
            get {
                return ResourceManager.GetString("AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto save on the.
        /// </summary>
        public static string AutoSaveOnDate {
            get {
                return ResourceManager.GetString("AutoSaveOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available on.
        /// </summary>
        public static string AvailableOn {
            get {
                return ResourceManager.GetString("AvailableOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Badges.
        /// </summary>
        public static string Badges {
            get {
                return ResourceManager.GetString("Badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse UWP apps.
        /// </summary>
        public static string BrowseUWPApps {
            get {
                return ResourceManager.GetString("BrowseUWPApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to launch Non-Win32 applications as an administrator..
        /// </summary>
        public static string CannotLaunchAsAdminUWP {
            get {
                return ResourceManager.GetString("CannotLaunchAsAdminUWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change BotGDX&apos;s current language..
        /// </summary>
        public static string ChangeLanguageDescription {
            get {
                return ResourceManager.GetString("ChangeLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to continue?.
        /// </summary>
        public static string ContinueInstall {
            get {
                return ResourceManager.GetString("ContinueInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to a Steam game.
        /// </summary>
        public static string ConvertToSteam {
            get {
                return ResourceManager.GetString("ConvertToSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Converting a EXE game to a Steam game is irreversible, are you sure you wanna continue?.
        /// </summary>
        public static string ConvertToSteamMsg {
            get {
                return ResourceManager.GetString("ConvertToSteamMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search for a game cover.
        /// </summary>
        public static string CoverSearch {
            get {
                return ResourceManager.GetString("CoverSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Crazy About It.
        /// </summary>
        public static string CrazyAboutIt {
            get {
                return ResourceManager.GetString("CrazyAboutIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mark a game as favorite..
        /// </summary>
        public static string CrazyAboutItDesc {
            get {
                return ResourceManager.GetString("CrazyAboutItDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a profile and to get started..
        /// </summary>
        public static string CreateAProfile {
            get {
                return ResourceManager.GetString("CreateAProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default page.
        /// </summary>
        public static string DefaultPage {
            get {
                return ResourceManager.GetString("DefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default page on startup.
        /// </summary>
        public static string DefaultPageOnStart {
            get {
                return ResourceManager.GetString("DefaultPageOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default view mode in Library.
        /// </summary>
        public static string DefaultViewMode {
            get {
                return ResourceManager.GetString("DefaultViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete selected game(s).
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you wanna delete these games? This operation can&apos;t be cancelled..
        /// </summary>
        public static string DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete profile.
        /// </summary>
        public static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete this profile?.
        /// </summary>
        public static string DeleteProfileMsg {
            get {
                return ResourceManager.GetString("DeleteProfileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete this tag.
        /// </summary>
        public static string DeleteTag {
            get {
                return ResourceManager.GetString("DeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete this tag? This will remove its association with the assigned games..
        /// </summary>
        public static string DeleteTagMsg {
            get {
                return ResourceManager.GetString("DeleteTagMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display hidden games.
        /// </summary>
        public static string DisplayHiddenGames {
            get {
                return ResourceManager.GetString("DisplayHiddenGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done!.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit game.
        /// </summary>
        public static string EditGame {
            get {
                return ResourceManager.GetString("EditGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add/Edit description.
        /// </summary>
        public static string EditGameDescription {
            get {
                return ResourceManager.GetString("EditGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable search keyboard shortcut.
        /// </summary>
        public static string EnableSearchShortcut {
            get {
                return ResourceManager.GetString("EnableSearchShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Epic Games Store.
        /// </summary>
        public static string EpicGamesStore {
            get {
                return ResourceManager.GetString("EpicGamesStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error has occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !.
        /// </summary>
        public static string ExclamationMark {
            get {
                return ResourceManager.GetString("ExclamationMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export your games.
        /// </summary>
        public static string ExportGames {
            get {
                return ResourceManager.GetString("ExportGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export your games in BotGDX to .botgdx save file..
        /// </summary>
        public static string ExportGamesDescription {
            get {
                return ResourceManager.GetString("ExportGamesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your games have been successfully exported..
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favorite/Unfavorite.
        /// </summary>
        public static string FavoriteButton {
            get {
                return ResourceManager.GetString("FavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is feature requires an Internet connection..
        /// </summary>
        public static string FeatureNeedsInternet {
            get {
                return ResourceManager.GetString("FeatureNeedsInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The specified file doesn&apos;t exist..
        /// </summary>
        public static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can add a game by clicking on the &quot;Add&quot; button on the home page or by draging in an executable file in the main page..
        /// </summary>
        public static string FirstRunAddGamesDescription {
            get {
                return ResourceManager.GetString("FirstRunAddGamesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FPS Counter.
        /// </summary>
        public static string FpsCounter {
            get {
                return ResourceManager.GetString("FpsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The opacity of the FPS Counter..
        /// </summary>
        public static string FpsCounterOpacity {
            get {
                return ResourceManager.GetString("FpsCounterOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card view.
        /// </summary>
        public static string GameCard {
            get {
                return ResourceManager.GetString("GameCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please complete the game&apos;s information..
        /// </summary>
        public static string GameFieldsEmpty {
            get {
                return ResourceManager.GetString("GameFieldsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Where all your games are gathered..
        /// </summary>
        public static string GameGathered {
            get {
                return ResourceManager.GetString("GameGathered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на game.
        /// </summary>
        public static string GameL {
            get {
                return ResourceManager.GetString("GameL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List view.
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A game needs an executable and a name..
        /// </summary>
        public static string GameNeedsName {
            get {
                return ResourceManager.GetString("GameNeedsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This game has no achievements..
        /// </summary>
        public static string GameNoAchievements {
            get {
                return ResourceManager.GetString("GameNoAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game Process.
        /// </summary>
        public static string GameProcess {
            get {
                return ResourceManager.GetString("GameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game Properties.
        /// </summary>
        public static string GameProperties {
            get {
                return ResourceManager.GetString("GameProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на games.
        /// </summary>
        public static string GamesL {
            get {
                return ResourceManager.GetString("GamesL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game tags.
        /// </summary>
        public static string GameTags {
            get {
                return ResourceManager.GetString("GameTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на G4V Files.
        /// </summary>
        public static string GavFiles {
            get {
                return ResourceManager.GetString("GavFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BotGDX needs to restart to apply changes..
        /// </summary>
        public static string BotGDXNeedsRestartChanges {
            get {
                return ResourceManager.GetString("BotGDXNeedsRestartChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get RAWG image.
        /// </summary>
        public static string GetRAWGImage {
            get {
                return ResourceManager.GetString("GetRAWGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GitHub.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go Forward.
        /// </summary>
        public static string GoForward {
            get {
                return ResourceManager.GetString("GoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello,.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hidden games.
        /// </summary>
        public static string HiddenGames {
            get {
                return ResourceManager.GetString("HiddenGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide this game.
        /// </summary>
        public static string HideGame {
            get {
                return ResourceManager.GetString("HideGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide the search bar.
        /// </summary>
        public static string HideSearchBar {
            get {
                return ResourceManager.GetString("HideSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hour.
        /// </summary>
        public static string HourMin {
            get {
                return ResourceManager.GetString("HourMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на h.
        /// </summary>
        public static string HourShort {
            get {
                return ResourceManager.GetString("HourShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hours.
        /// </summary>
        public static string HoursMin {
            get {
                return ResourceManager.GetString("HoursMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The specified image doesn&apos;t exist..
        /// </summary>
        public static string ImageNotExist {
            get {
                return ResourceManager.GetString("ImageNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The current games are going to be replaced by the new ones, you cannot revert this operation. Do you wanna continue?.
        /// </summary>
        public static string ImportConfirmMsg {
            get {
                return ResourceManager.GetString("ImportConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import your games.
        /// </summary>
        public static string ImportGames {
            get {
                return ResourceManager.GetString("ImportGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import a .botgdx save file in BotGDX. The current save file is going to be replaced by the new one..
        /// </summary>
        public static string ImportGamesDescription {
            get {
                return ResourceManager.GetString("ImportGamesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you were a previous user, you may wanna import an existing &quot;.botgdx&quot; save file..
        /// </summary>
        public static string ImportGamesFirstRunDescription {
            get {
                return ResourceManager.GetString("ImportGamesFirstRunDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your games have been successfully imported..
        /// </summary>
        public static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please specify a correct value..
        /// </summary>
        public static string IncorrectValue {
            get {
                return ResourceManager.GetString("IncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Infos.
        /// </summary>
        public static string Infos {
            get {
                return ResourceManager.GetString("Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Integrations.
        /// </summary>
        public static string Integrations {
            get {
                return ResourceManager.GetString("Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of games must be higher than 0..
        /// </summary>
        public static string InvalidGameNumber {
            get {
                return ResourceManager.GetString("InvalidGameNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keyboard shortcut.
        /// </summary>
        public static string KeybordShortcut {
            get {
                return ResourceManager.GetString("KeybordShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last use.
        /// </summary>
        public static string LastTimePlayed {
            get {
                return ResourceManager.GetString("LastTimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launch game as administrator..
        /// </summary>
        public static string LaunchGameAsAdmin {
            get {
                return ResourceManager.GetString("LaunchGameAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Least played.
        /// </summary>
        public static string LeastPlayed {
            get {
                return ResourceManager.GetString("LeastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Legendary Gamer.
        /// </summary>
        public static string LegendaryGamer {
            get {
                return ResourceManager.GetString("LegendaryGamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play at least 5000 hours, no matter which game..
        /// </summary>
        public static string LegendaryGamerDesc {
            get {
                return ResourceManager.GetString("LegendaryGamerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let&apos;s go!.
        /// </summary>
        public static string LetsGo {
            get {
                return ResourceManager.GetString("LetsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A long time ago.
        /// </summary>
        public static string LongTimeAgo {
            get {
                return ResourceManager.GetString("LongTimeAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BotGDX.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Make autosaves.
        /// </summary>
        public static string MakeAutoSaves {
            get {
                return ResourceManager.GetString("MakeAutoSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Make backup now.
        /// </summary>
        public static string MakeBackup {
            get {
                return ResourceManager.GetString("MakeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create, edit or remove your game tags..
        /// </summary>
        public static string ManageGameTags {
            get {
                return ResourceManager.GetString("ManageGameTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max number of games shown in the &quot;Recent&quot; section..
        /// </summary>
        public static string MaxNumberOfRecentGames {
            get {
                return ResourceManager.GetString("MaxNumberOfRecentGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microsoft Store.
        /// </summary>
        public static string MicrosoftStore {
            get {
                return ResourceManager.GetString("MicrosoftStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Migrate from v3.
        /// </summary>
        public static string MigrateFromV3 {
            get {
                return ResourceManager.GetString("MigrateFromV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на minute.
        /// </summary>
        public static string MinuteMin {
            get {
                return ResourceManager.GetString("MinuteMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на minutes.
        /// </summary>
        public static string MinutesMin {
            get {
                return ResourceManager.GetString("MinutesMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Misc.
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на January,Febuary,March,April,May,June,July,August,September,October,November,December.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Most played.
        /// </summary>
        public static string MostPlayed {
            get {
                return ResourceManager.GetString("MostPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Badges.
        /// </summary>
        public static string MyBadges {
            get {
                return ResourceManager.GetString("MyBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please specify a name..
        /// </summary>
        public static string NameNeededMsg {
            get {
                return ResourceManager.GetString("NameNeededMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Need Space On The Shelves.
        /// </summary>
        public static string NeedSpaceOnTheShelves {
            get {
                return ResourceManager.GetString("NeedSpaceOnTheShelves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Have more than 50 games in your Library..
        /// </summary>
        public static string NeedSpaceOnTheShelvesDesc {
            get {
                return ResourceManager.GetString("NeedSpaceOnTheShelvesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BotGDX hasn&apos;t found any achievements in the RAWG.io database, or this game is not associated with RAWG..
        /// </summary>
        public static string NoAchivementsMsg {
            get {
                return ResourceManager.GetString("NoAchivementsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no informations to display..
        /// </summary>
        public static string NoGames {
            get {
                return ResourceManager.GetString("NoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No items found.
        /// </summary>
        public static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You don&apos;t have any notifications..
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Noob Player.
        /// </summary>
        public static string NoobPlayer {
            get {
                return ResourceManager.GetString("NoobPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play at least one hour, no matter which game..
        /// </summary>
        public static string NoobPlayerDesc {
            get {
                return ResourceManager.GetString("NoobPlayerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No profiles have been found..
        /// </summary>
        public static string NoProfilesFound {
            get {
                return ResourceManager.GetString("NoProfilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This game has no ratings..
        /// </summary>
        public static string NoRatings {
            get {
                return ResourceManager.GetString("NoRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no ratings for this game because either it&apos;s not connected to RAWG.io, or because no one has rated the game..
        /// </summary>
        public static string NoRatingsAv {
            get {
                return ResourceManager.GetString("NoRatingsAv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We haven&apos;t found any games you might like..
        /// </summary>
        public static string NoRecommandedGames {
            get {
                return ResourceManager.GetString("NoRecommandedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is currently no statistics to show..
        /// </summary>
        public static string NoStatistics {
            get {
                return ResourceManager.GetString("NoStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not associated.
        /// </summary>
        public static string NotAssociated {
            get {
                return ResourceManager.GetString("NotAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notification center.
        /// </summary>
        public static string NotificationCenter {
            get {
                return ResourceManager.GetString("NotificationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на notification..
        /// </summary>
        public static string NotificationLower {
            get {
                return ResourceManager.GetString("NotificationLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на notifications..
        /// </summary>
        public static string NotificationsLower {
            get {
                return ResourceManager.GetString("NotificationsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are not logged in to Steam..
        /// </summary>
        public static string NotLoggedToSteam {
            get {
                return ResourceManager.GetString("NotLoggedToSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of results to display.
        /// </summary>
        public static string NumberResults {
            get {
                return ResourceManager.GetString("NumberResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на of the month..
        /// </summary>
        public static string OfMonth {
            get {
                return ResourceManager.GetString("OfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On startup.
        /// </summary>
        public static string OnStartup {
            get {
                return ResourceManager.GetString("OnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opacity.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press {0} to open the FPS Counter..
        /// </summary>
        public static string OpenFpsCounter {
            get {
                return ResourceManager.GetString("OpenFpsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other profiles.
        /// </summary>
        public static string OtherProfiles {
            get {
                return ResourceManager.GetString("OtherProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #1.
        /// </summary>
        public static string P1 {
            get {
                return ResourceManager.GetString("P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #2.
        /// </summary>
        public static string P2 {
            get {
                return ResourceManager.GetString("P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #3.
        /// </summary>
        public static string P3 {
            get {
                return ResourceManager.GetString("P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;PackageFamilyName&quot; property.
        /// </summary>
        public static string PackageFamilyName {
            get {
                return ResourceManager.GetString("PackageFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your Games;Recent Games;List view.
        /// </summary>
        public static string PagesNames {
            get {
                return ResourceManager.GetString("PagesNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pin/Unpin window.
        /// </summary>
        public static string PinUnpinWindow {
            get {
                return ResourceManager.GetString("PinUnpinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Platforms.
        /// </summary>
        public static string Platforms {
            get {
                return ResourceManager.GetString("Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PLAY.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play.
        /// </summary>
        public static string PlayLowerCase {
            get {
                return ResourceManager.GetString("PlayLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play {0}.
        /// </summary>
        public static string PlayTo {
            get {
                return ResourceManager.GetString("PlayTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BotGDX - Menu.
        /// </summary>
        public static string PopupMenu {
            get {
                return ResourceManager.GetString("PopupMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The process to look for when the game is running. It allows the possibility to count the time you played the game. Keep the field empty to use the default executable..
        /// </summary>
        public static string ProcessNameHelp {
            get {
                return ResourceManager.GetString("ProcessNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Progress made:.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random game.
        /// </summary>
        public static string RandomGame {
            get {
                return ResourceManager.GetString("RandomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ratings.
        /// </summary>
        public static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BotGDX is integrated with the RAWG.io database, which means that BotGDX can automatically find covers, descriptions, and other informations about a game..
        /// </summary>
        public static string RAWGDescriptionFirstRun {
            get {
                return ResourceManager.GetString("RAWGDescriptionFirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RAWG Database integration.
        /// </summary>
        public static string RAWGIntegration {
            get {
                return ResourceManager.GetString("RAWGIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RAWG.io.
        /// </summary>
        public static string RAWGio {
            get {
                return ResourceManager.GetString("RAWGio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Powered by RAWG.io.
        /// </summary>
        public static string RAWGPowered {
            get {
                return ResourceManager.GetString("RAWGPowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are now ready to use BotGDX..
        /// </summary>
        public static string ReadyFirstRun {
            get {
                return ResourceManager.GetString("ReadyFirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Games recently played.
        /// </summary>
        public static string RecentGames {
            get {
                return ResourceManager.GetString("RecentGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recents.
        /// </summary>
        public static string Recents {
            get {
                return ResourceManager.GetString("Recents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You may like....
        /// </summary>
        public static string RecommandedGames {
            get {
                return ResourceManager.GetString("RecommandedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;You may like...&quot; section.
        /// </summary>
        public static string RecommandedGamesSection {
            get {
                return ResourceManager.GetString("RecommandedGamesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings related to the &quot;You may like...&quot; section..
        /// </summary>
        public static string RecommandedSettings {
            get {
                return ResourceManager.GetString("RecommandedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset settings.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset settings to their default values..
        /// </summary>
        public static string ResetSettingsDesc {
            get {
                return ResourceManager.GetString("ResetSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to reset ALL settings? This operation is irreversible..
        /// </summary>
        public static string ResetSettingsMsg {
            get {
                return ResourceManager.GetString("ResetSettingsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save file location.
        /// </summary>
        public static string SaveLocation {
            get {
                return ResourceManager.GetString("SaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Options.
        /// </summary>
        public static string SaveOptions {
            get {
                return ResourceManager.GetString("SaveOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save settings..
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan a directory.
        /// </summary>
        public static string ScanDirectory {
            get {
                return ResourceManager.GetString("ScanDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Screenshots.
        /// </summary>
        public static string Screenshots {
            get {
                return ResourceManager.GetString("Screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search bar.
        /// </summary>
        public static string SearchBar {
            get {
                return ResourceManager.GetString("SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string SearchF {
            get {
                return ResourceManager.GetString("SearchF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keyboard shortcut related settings..
        /// </summary>
        public static string SearchKeyboardShortcutDesc {
            get {
                return ResourceManager.GetString("SearchKeyboardShortcutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на second.
        /// </summary>
        public static string SecondMin {
            get {
                return ResourceManager.GetString("SecondMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на seconds.
        /// </summary>
        public static string SecondsMin {
            get {
                return ResourceManager.GetString("SecondsMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на See the GitHub repository..
        /// </summary>
        public static string SeeGitHubRepo {
            get {
                return ResourceManager.GetString("SeeGitHubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на See licenses.
        /// </summary>
        public static string SeeLicenses {
            get {
                return ResourceManager.GetString("SeeLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на See on RAWG.
        /// </summary>
        public static string SeeOnRAWG {
            get {
                return ResourceManager.GetString("SeeOnRAWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a directory.
        /// </summary>
        public static string SelectADirectory {
            get {
                return ResourceManager.GetString("SelectADirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a game or drag and drop it here.
        /// </summary>
        public static string SelectDragDropGame {
            get {
                return ResourceManager.GetString("SelectDragDropGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a game.
        /// </summary>
        public static string SelectGame {
            get {
                return ResourceManager.GetString("SelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select games.
        /// </summary>
        public static string SelectGames {
            get {
                return ResourceManager.GetString("SelectGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select games to import..
        /// </summary>
        public static string SelectGamesImport {
            get {
                return ResourceManager.GetString("SelectGamesImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a game to begin.
        /// </summary>
        public static string SelectGameStart {
            get {
                return ResourceManager.GetString("SelectGameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select notifications you want to receive in Notification Center..
        /// </summary>
        public static string SelectNotification {
            get {
                return ResourceManager.GetString("SelectNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show games that you haven&apos;t played in a while..
        /// </summary>
        public static string ShowMoreUnplayedGames {
            get {
                return ResourceManager.GetString("ShowMoreUnplayedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show screenshots.
        /// </summary>
        public static string ShowScreenshots {
            get {
                return ResourceManager.GetString("ShowScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sidebar.
        /// </summary>
        public static string Sidebar {
            get {
                return ResourceManager.GetString("Sidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sidebar position..
        /// </summary>
        public static string SidebarPosition {
            get {
                return ResourceManager.GetString("SidebarPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skip this step.
        /// </summary>
        public static string SkipStep {
            get {
                return ResourceManager.GetString("SkipStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort alphabetically.
        /// </summary>
        public static string SortAlphabetically {
            get {
                return ResourceManager.GetString("SortAlphabetically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort in reverse order.
        /// </summary>
        public static string SortInverse {
            get {
                return ResourceManager.GetString("SortInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spotlight.
        /// </summary>
        public static string Spotlight {
            get {
                return ResourceManager.GetString("Spotlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start by adding a game.
        /// </summary>
        public static string StartAddGame {
            get {
                return ResourceManager.GetString("StartAddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starter Gamer.
        /// </summary>
        public static string StarterGamer {
            get {
                return ResourceManager.GetString("StarterGamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play at least 10 hours, no matter which game..
        /// </summary>
        public static string StarterGamerDesc {
            get {
                return ResourceManager.GetString("StarterGamerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Startup.
        /// </summary>
        public static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose the startup page on startup..
        /// </summary>
        public static string StartupPage {
            get {
                return ResourceManager.GetString("StartupPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LAST USAGE.
        /// </summary>
        public static string StatsLastTimePlayed {
            get {
                return ResourceManager.GetString("StatsLastTimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TOTAL TIME PLAYED.
        /// </summary>
        public static string StatsTimePlayed {
            get {
                return ResourceManager.GetString("StatsTimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steam.
        /// </summary>
        public static string Steam {
            get {
                return ResourceManager.GetString("Steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steam App ID.
        /// </summary>
        public static string SteamAppId {
            get {
                return ResourceManager.GetString("SteamAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot run this steam game as it is not installed..
        /// </summary>
        public static string SteamAppNotInstalled {
            get {
                return ResourceManager.GetString("SteamAppNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot launch game: Steam is not running..
        /// </summary>
        public static string SteamNotRunning {
            get {
                return ResourceManager.GetString("SteamNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stores.
        /// </summary>
        public static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch profile.
        /// </summary>
        public static string SwitchProfile {
            get {
                return ResourceManager.GetString("SwitchProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Themes.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set the theme of BotGDX..
        /// </summary>
        public static string ThemesDesc {
            get {
                return ResourceManager.GetString("ThemesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import a theme.
        /// </summary>
        public static string ThemesImport {
            get {
                return ResourceManager.GetString("ThemesImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Start.
        /// </summary>
        public static string TheStart {
            get {
                return ResourceManager.GetString("TheStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a game..
        /// </summary>
        public static string TheStartDesc {
            get {
                return ResourceManager.GetString("TheStartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This Week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TOP 10 MOST PLAYED GAMES.
        /// </summary>
        public static string Top10MostPlayedGames {
            get {
                return ResourceManager.GetString("Top10MostPlayedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time played.
        /// </summary>
        public static string TotalTimePlayed {
            get {
                return ResourceManager.GetString("TotalTimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на True Gamer.
        /// </summary>
        public static string TrueGamer {
            get {
                return ResourceManager.GetString("TrueGamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play at least 1000 hours, no matter which game..
        /// </summary>
        public static string TrueGamerDesc {
            get {
                return ResourceManager.GetString("TrueGamerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You haven&apos;t played {0} since a while..
        /// </summary>
        public static string UnusedGame {
            get {
                return ResourceManager.GetString("UnusedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unused game.
        /// </summary>
        public static string UnusedGameNotification {
            get {
                return ResourceManager.GetString("UnusedGameNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updates available.
        /// </summary>
        public static string UpdateAv {
            get {
                return ResourceManager.GetString("UpdateAv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updates are available for BotGDX:.
        /// </summary>
        public static string UpdateAvMessage {
            get {
                return ResourceManager.GetString("UpdateAvMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updates are available for BotGDX..
        /// </summary>
        public static string UpdateAvMessageNotify {
            get {
                return ResourceManager.GetString("UpdateAvMessageNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No updates available.
        /// </summary>
        public static string UpdateUn {
            get {
                return ResourceManager.GetString("UpdateUn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No updates are currently available..
        /// </summary>
        public static string UpdateUnMessage {
            get {
                return ResourceManager.GetString("UpdateUnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version:.
        /// </summary>
        public static string UpdateVersion {
            get {
                return ResourceManager.GetString("UpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to BotGDX.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на When you will start playing games, they will show up here..
        /// </summary>
        public static string WelcomeRecentGames {
            get {
                return ResourceManager.GetString("WelcomeRecentGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What game do you want to play?.
        /// </summary>
        public static string WhatGameToPlay {
            get {
                return ResourceManager.GetString("WhatGameToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Xalyus Updater doesn&apos;t exist, please reinstall BotGDX..
        /// </summary>
        public static string XUDoesNotExist {
            get {
                return ResourceManager.GetString("XUDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have.
        /// </summary>
        public static string YouHave {
            get {
                return ResourceManager.GetString("YouHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your Games.
        /// </summary>
        public static string YourGames {
            get {
                return ResourceManager.GetString("YourGames", resourceCulture);
            }
        }
    }
}
